**Rahul Sharma** arrived in Mumbai(a city in India) with the aim of finding a suitable house that fits his budget and location preferences. He has some queries related to house selection and is seeking solutions.

Help Rahul Sharma to answer his questions and you are provided with a sample dataset of house information that contain area_type, availability, location, size, society, total_sqft, bath, balcony, and price.

In [1]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file 'bengaluru_house_prices.csv' and store it in variable 'df'.
- print the number of rows and columns in it
- print the Top 5 rows

In [2]:
#read the csv file
df=pd.read_csv("mumbai_house_prices.csv")

#show the number of rows and columns in dataframe 'df'

df

#show Top5 rows
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,Ready To Move,Andheri,3 BHK,NaN,1920,4.0,2.0,121.0
1,Plot Area,18-Aug,Bandra,4 Bedroom,ValleCi,1500,4.0,3.0,192.0
2,Super built-up Area,Ready To Move,Powai,2 BHK,Sothin,925,2.0,1.0,55.0
3,Plot Area,Ready To Move,Thane,2 Bedroom,NaN,500,1.0,0.0,55.0
4,Super built-up Area,Ready To Move,Navi Mumbai,2 BHK,Prncyrn,1174,2.0,1.0,74.0

In [3]:
df.shape

(50, 9)

### <font color="purple">**Question2**</font>
- show the unique categories present in **'area_type'** and **'size'** columns

In [4]:
#unique values in 'area_type' column
df.area_type.unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [5]:
#unique values in 'size' column
df['size'].unique()

array(['3 BHK', '4 Bedroom', '2 BHK', '2 Bedroom', '1 BHK', '5 BHK',
       '3 Bedroom', '5 Bedroom', '1 Bedroom'], dtype=object)

### <font color="purple">**Question3**</font>
- Filter data which have **'2 BHK'** house size and area_type of **'Super built-up  Area'**
- Also get the count of such rows

In [6]:
#filter the data
df[df['size']=='2 BHK']

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
2,Super built-up Area,Ready To Move,Powai,2 BHK,Sothin,925,2.0,1.0,55.00
4,Super built-up Area,Ready To Move,Navi Mumbai,2 BHK,Prncyrn,1174,2.0,1.0,74.00
5,Super built-up Area,Ready To Move,Dadar,2 BHK,HRaniIb,1202,2.0,1.0,79.00
8,Super built-up Area,Ready To Move,Goregaon,2 BHK,ShdhiSa,1200,2.0,2.0,79.55
11,Super built-up Area,17-Oct,Worli,2 BHK,ViistLa,1235,2.0,1.0,52.04
14,Super built-up Area,Ready To Move,Vashi,2 BHK,PrityTr,1153,2.0,2.0,56.55
21,Super built-up Area,18-Apr,Bandra,2 BHK,NaN,1120,2.0,2.0,40.00
24,Super built-up Area,Ready To Move,Navi Mumbai,2 BHK,GeereEc,1363,2.0,2.0,68.00
25,Super built-up Area,Ready To Move,Dadar,2 BHK,NaN,1175,2.0,2.0,42.00
30,Built-up Area,Ready To Move,Chembur,2 BHK,NaN,850,2.0,0.0,35.00
32,Super built-up Area,Ready To Move,Lower Parel,2 BHK,Pyikad,1274,2.0,2.0,48.42
33,Super built-up Area,Ready To Move,Mulund,2 BHK,CMard B,1005,2.0,1.0,55.00
35,Super built-up Area,17-Mar,Khar,2 BHK,Uptusol,1385,2.0,3.0,80.00
36,Built-up Area,Ready To Move,Santacruz,2 BHK,NaN,1125,2.0,1.0,46.00
37,Super built-up Area,Ready To Move,Kurla,2 BHK,Sriferi,1176,2.0,2.0,50.00
38,Super built-up Area,Ready To Move,Colaba,2 BHK,GMown E,770,1.0,1.0,40.00
39,Super built-up Area,Ready To Move,Panvel,2 BHK,NaN,1195,2.0,1.0,35.84
41,Super built-up Area,Ready To Move,Bandra,2 BHK,Prrtht,883,2.0,1.0,37.00
42,Super built-up Area,Ready To Move,Powai,2 BHK,RInceeg,1243,2.0,2.0,46.00
45,Super built-up Area,Ready To Move,Dadar,2 BHK,NaN,1200,2.0,3.0,120.00
46,Built-up Area,Ready To Move,Borivali,2 BHK,NaN,936,2.0,0.0,40.20
48,Super built-up Area,Ready To Move,Goregaon,2 BHK,Maidsr,1075,2.0,2.0,45.00
49,Super built-up Area,Ready To Move,Juhu,2 BHK,NaN,1225,2.0,1.0,47.00

In [7]:
#show the number of rows for the filtered data
df[df['size']=='2 BHK'].area_type.count()

np.int64(23)

### <font color="purple">**Question4**</font>
- Add a new column **'price_category'** which contain a category based on the price of house.
- If price of house is less than 80, **"Affordable"**, otherwise **"High Cost"**

In [8]:
#Add the column 'price_category'
def price_category(row):
    if(row['price']<80):
        return "Affordable"
    return "High Cost"
df['price_category']=df.apply(price_category,axis=1);
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_category
0,Super built-up Area,Ready To Move,Andheri,3 BHK,NaN,1920,4.0,2.0,121.00,High Cost
1,Plot Area,18-Aug,Bandra,4 Bedroom,ValleCi,1500,4.0,3.0,192.00,High Cost
2,Super built-up Area,Ready To Move,Powai,2 BHK,Sothin,925,2.0,1.0,55.00,Affordable
3,Plot Area,Ready To Move,Thane,2 Bedroom,NaN,500,1.0,0.0,55.00,Affordable
4,Super built-up Area,Ready To Move,Navi Mumbai,2 BHK,Prncyrn,1174,2.0,1.0,74.00,Affordable
5,Super built-up Area,Ready To Move,Dadar,2 BHK,HRaniIb,1202,2.0,1.0,79.00,Affordable
6,Super built-up Area,18-May,Borivali,3 BHK,NaN,1250,2.0,2.0,44.00,Affordable
7,Super built-up Area,21-Dec,Malad,1 BHK,PrarePa,525,1.0,1.0,26.00,Affordable
8,Super built-up Area,Ready To Move,Goregaon,2 BHK,ShdhiSa,1200,2.0,2.0,79.55,Affordable
9,Plot Area,Ready To Move,Juhu,4 Bedroom,Adowslm,3100,4.0,2.0,350.00,High Cost
10,Super built-up Area,Ready To Move,Chembur,3 BHK,JRrnauv,1550,3.0,3.0,65.10,Affordable
11,Super built-up Area,17-Oct,Worli,2 BHK,ViistLa,1235,2.0,1.0,52.04,Affordable
12,Super built-up Area,18-May,Lower Parel,3 BHK,ViistLa,1475,2.0,2.0,63.00,Affordable
13,Super built-up Area,Ready To Move,Mulund,3 BHK,SNity S,1520,2.0,3.0,81.00,High Cost
14,Super built-up Area,Ready To Move,Vashi,2 BHK,PrityTr,1153,2.0,2.0,56.55,Affordable
15,Super built-up Area,18-Aug,Khar,1 BHK,SunceEs,645,1.0,1.0,16.45,Affordable
16,Super built-up Area,18-Dec,Santacruz,3 BHK,Mahosya,1920,3.0,2.0,134.00,High Cost
17,Super built-up Area,Ready To Move,Kurla,3 BHK,J axyGa,1300,2.0,2.0,75.00,Affordable
18,Built-up Area,Ready To Move,Colaba,5 BHK,NaN,3600,5.0,3.0,145.00,High Cost
19,Super built-up Area,Ready To Move,Panvel,3 BHK,Sovar S,1530,2.0,2.0,74.40,Affordable
20,Super built-up Area,Ready To Move,Andheri,3 BHK,VDenaWa,2800,3.0,2.0,250.00,High Cost
21,Super built-up Area,18-Apr,Bandra,2 BHK,NaN,1120,2.0,2.0,40.00,Affordable
22,Built-up Area,Ready To Move,Powai,3 BHK,Keort F,1500,3.0,2.0,75.00,Affordable
23,Super built-up Area,18-May,Thane,3 BHK,NaN,1115,3.0,1.0,39.14,Affordable
24,Super built-up Area,Ready To Move,Navi Mumbai,2 BHK,GeereEc,1363,2.0,2.0,68.00,Affordable
25,Super built-up Area,Ready To Move,Dadar,2 BHK,NaN,1175,2.0,2.0,42.00,Affordable
26,Super built-up Area,Ready To Move,Borivali,3 BHK,BrdgeNo,1710,3.0,2.0,110.00,High Cost
27,Carpet Area,Ready To Move,Malad,4 Bedroom,NaN,2100,3.0,0.0,210.00,High Cost
28,Super built-up Area,Ready To Move,Goregaon,3 BHK,NaN,1340,2.0,2.0,53.60,Affordable
29,Plot Area,Ready To Move,Juhu,3 Bedroom,NaN,980,3.0,1.0,80.00,High Cost
30,Built-up Area,Ready To Move,Chembur,2 BHK,NaN,850,2.0,0.0,35.00,Affordable
31,Super built-up Area,Ready To Move,Worli,3 BHK,Sahtsva,1354,3.0,1.0,90.00,High Cost
32,Super built-up Area,Ready To Move,Lower Parel,2 BHK,Pyikad,1274,2.0,2.0,48.42,Affordable
33,Super built-up Area,Ready To Move,Mulund,2 BHK,CMard B,1005,2.0,1.0,55.00,Affordable
34,Super built-up Area,Ready To Move,Vashi,3 BHK,NaN,1355,2.0,3.0,58.25,Affordable
35,Super built-up Area,17-Mar,Khar,2 BHK,Uptusol,1385,2.0,3.0,80.00,High Cost
36,Built-up Area,Ready To Move,Santacruz,2 BHK,NaN,1125,2.0,1.0,46.00,Affordable
37,Super built-up Area,Ready To Move,Kurla,2 BHK,Sriferi,1176,2.0,2.0,50.00,Affordable
38,Super built-up Area,Ready To Move,Colaba,2 BHK,GMown E,770,1.0,1.0,40.00,Affordable
39,Super built-up Area,Ready To Move,Panvel,2 BHK,NaN,1195,2.0,1.0,35.84,Affordable
40,Plot Area,Ready To Move,Andheri,3 Bedroom,CoinoCu,2500,3.0,2.0,190.00,High Cost
41,Super built-up Area,Ready To Move,Bandra,2 BHK,Prrtht,883,2.0,1.0,37.00,Affordable
42,Super built-up Area,Ready To Move,Powai,2 BHK,RInceeg,1243,2.0,2.0,46.00,Affordable
43,Built-up Area,Ready To Move,Thane,5 Bedroom,NaN,2800,5.0,3.0,130.00,High Cost
44,Plot Area,Ready To Move,Navi Mumbai,1 Bedroom,NaN,410,1.0,1.0,48.00,Affordable
45,Super built-up Area,Ready To Move,Dadar,2 BHK,NaN,1200,2.0,3.0,120.00,High Cost
46,Built-up Area,Ready To Move,Borivali,2 BHK,NaN,936,2.0,0.0,40.20,Affordable
47,Super built-up Area,Ready To Move,Malad,3 BHK,NaN,1464,3.0,2.0,56.00,Affordable
48,Super built-up Area,Ready To Move,Goregaon,2 BHK,Maidsr,1075,2.0,2.0,45.00,Affordable
49,Super built-up Area,Ready To Move,Juhu,2 BHK,NaN,1225,2.0,1.0,47.00,Affordable

In [9]:
#show the updated dataframe: top5 rows
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_category
0,Super built-up Area,Ready To Move,Andheri,3 BHK,NaN,1920,4.0,2.0,121.0,High Cost
1,Plot Area,18-Aug,Bandra,4 Bedroom,ValleCi,1500,4.0,3.0,192.0,High Cost
2,Super built-up Area,Ready To Move,Powai,2 BHK,Sothin,925,2.0,1.0,55.0,Affordable
3,Plot Area,Ready To Move,Thane,2 Bedroom,NaN,500,1.0,0.0,55.0,Affordable
4,Super built-up Area,Ready To Move,Navi Mumbai,2 BHK,Prncyrn,1174,2.0,1.0,74.0,Affordable

### <font color="purple">**Question5**</font>

- Get all the rows that has prices greater than **mean/average** price of all houses

In [10]:
#write condition here
df.price.mean()

np.float64(82.07080000000002)