In [71]:
import pandas as pd

In [72]:
df=pd.read_csv("Movie_Analysis.csv")

In [73]:
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Avengers: Endgame,Hollywood,2019,8.2,Marvel Studios,400.00,2798.0,Millions,USD,English
1,The Dark Knight Returns,Hollywood,2008,9.1,Syncopy,185.00,1006.0,Millions,USD,English
2,Thor: Love and Thunder,Hollywood,2022,6.9,Marvel Studios,250.00,670.0,Millions,USD,English
3,The Kashmir Files Legacy,Bollywood,2022,8.1,Zee Studios,250.00,3409.0,Millions,INR,Hindi
4,RRR,Bollywood,2022,7.9,DVV Entertainment,5.50,12.0,Billions,INR,Telugu
5,Taare Zameen Par Redux,Bollywood,2007,8.2,NaN,120.00,1350.0,Millions,INR,Hindi
6,Interstellar Legacy,Hollywood,2014,8.7,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,Munna Bhai M.B.B.S. Returns,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi
8,Bajirao Mastani Saga,Bollywood,2015,7.3,NaN,1.40,3.5,Billions,INR,Hindi
9,Parasite Redux,Hollywood,2019,8.7,NaN,15.50,263.1,Millions,USD,English
10,Gladiator Redux,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
11,Jurassic Park Saga,Hollywood,1993,8.1,Universal Pictures,63.00,1046.0,Millions,USD,English
12,The Godfather Saga,Hollywood,1972,9.1,Paramount Pictures,7.20,291.0,Millions,USD,English
13,Shershaah Returns,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi
14,Titanic Saga,Hollywood,1997,8.1,Paramount Pictures,200.00,2202.0,Millions,USD,English
15,Captain America: The First Avenger Reborn,Hollywood,2011,6.8,Marvel Studios,216.70,370.6,Millions,USD,English
16,Pather Panchali Saga,Bollywood,1955,8.1,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali
17,Race 3,Bollywood,2018,1.7,Salman Khan Films,1.80,3.1,Billions,INR,Hindi
18,The Shawshank Redemption,Hollywood,1994,9.2,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
19,Avatar,Hollywood,2009,7.7,20th Century Fox,237.00,2847.0,Millions,USD,English
20,Doctor Strange in the Multiverse of Madness Redux,Hollywood,2022,7.1,Marvel Studios,200.00,954.8,Millions,USD,English
21,PK Redux,Bollywood,2014,8.2,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi
22,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.1,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi
23,Thor: The Dark World Reborn,Hollywood,2013,6.9,Marvel Studios,165.00,644.8,Millions,USD,English
24,Baahubali: The Beginning,Bollywood,2015,7.9,Arka Media Works,1.80,6.5,Billions,INR,Telugu
25,Pushpa: The Rise - Part 1 Legacy,Bollywood,2021,7.5,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu
26,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
27,K.G.F: Chapter 2,Bollywood,2022,8.3,Hombale Films,1.00,12.5,Billions,INR,Kannada
28,Kabhi Khushi Kabhie Gham Saga,Bollywood,2001,7.3,Dharma Productions,390.00,1360.0,Millions,INR,Hindi
29,Bajrangi Bhaijaan,Bollywood,2015,8.0,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi
30,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
31,3 Idiots,Bollywood,2009,8.6,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi
32,Avengers: Infinity War Redux,Hollywood,2018,8.3,Marvel Studios,400.00,2048.0,Millions,USD,English
33,Captain America: The Winter Soldier,Hollywood,2014,7.9,Marvel Studios,177.00,714.4,Millions,USD,English
34,The Pursuit of Happyness Saga,Hollywood,2006,8.1,Columbia Pictures,55.00,307.1,Millions,USD,English
35,Schindler's List,Hollywood,1993,8.8,Universal Pictures,22.00,322.2,Millions,USD,English
36,Sanju Reborn,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi

In [74]:
Total_Number_Of_Movies=df.title.size
print("Total Number Of Movies In The List:",Total_Number_Of_Movies)

Total Number Of Movies In The List: 37

In [75]:
Total_Number_Of_Studios=df.studio.unique().size
print("Total Number Of Studio:",Total_Number_Of_Studios)

Total Number Of Studio: 22

In [76]:
Total_Number_Of_Languages=df.language.unique().size
print("Total Number Of Languages:",Total_Number_Of_Languages)

Total Number Of Languages: 5

In [77]:
Highest_IMDB_Rating=df[df.imdb_rating==df.imdb_rating.max()]
Highest_IMDB_Rating

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
18,The Shawshank Redemption,Hollywood,1994,9.2,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [78]:
Lowest_IMDB_Rating=df[df.imdb_rating==df.imdb_rating.min()]
Lowest_IMDB_Rating

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
17,Race 3,Bollywood,2018,1.7,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [79]:
Highest_Revenue_USD=df[df.currency=="USD"]
Highest_Revenue_USD[Highest_Revenue_USD.revenue==Highest_Revenue_USD.revenue.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
19,Avatar,Hollywood,2009,7.7,20th Century Fox,237.0,2847.0,Millions,USD,English

In [80]:
Lowest_Revenue_Movie=df[df.unit=="Thousands"]
Lowest_Revenue_Movie[Lowest_Revenue_Movie.revenue==Lowest_Revenue_Movie.revenue.min()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
16,Pather Panchali Saga,Bollywood,1955,8.1,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali

In [81]:
Highest_Budget_Movie=df[df.currency=="USD"]
Highest_Budget_Movie[Highest_Budget_Movie.budget==Highest_Budget_Movie.budget.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Avengers: Endgame,Hollywood,2019,8.2,Marvel Studios,400.0,2798.0,Millions,USD,English
32,Avengers: Infinity War Redux,Hollywood,2018,8.3,Marvel Studios,400.0,2048.0,Millions,USD,English

In [82]:
Lowest_Budget_INR=df[df.currency=="INR"]
Lowest_Budget_INR[Lowest_Budget_INR.budget==Lowest_Budget_INR.budget.min()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
27,K.G.F: Chapter 2,Bollywood,2022,8.3,Hombale Films,1.0,12.5,Billions,INR,Kannada
36,Sanju Reborn,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi

In [83]:
df["Profit"]=df.apply(lambda x:x["revenue"]-x["budget"],axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit
0,Avengers: Endgame,Hollywood,2019,8.2,Marvel Studios,400.00,2798.0,Millions,USD,English,2398.00
1,The Dark Knight Returns,Hollywood,2008,9.1,Syncopy,185.00,1006.0,Millions,USD,English,821.00
2,Thor: Love and Thunder,Hollywood,2022,6.9,Marvel Studios,250.00,670.0,Millions,USD,English,420.00
3,The Kashmir Files Legacy,Bollywood,2022,8.1,Zee Studios,250.00,3409.0,Millions,INR,Hindi,3159.00
4,RRR,Bollywood,2022,7.9,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,6.50
5,Taare Zameen Par Redux,Bollywood,2007,8.2,NaN,120.00,1350.0,Millions,INR,Hindi,1230.00
6,Interstellar Legacy,Hollywood,2014,8.7,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,536.80
7,Munna Bhai M.B.B.S. Returns,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,310.00
8,Bajirao Mastani Saga,Bollywood,2015,7.3,NaN,1.40,3.5,Billions,INR,Hindi,2.10
9,Parasite Redux,Hollywood,2019,8.7,NaN,15.50,263.1,Millions,USD,English,247.60
10,Gladiator Redux,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,357.50
11,Jurassic Park Saga,Hollywood,1993,8.1,Universal Pictures,63.00,1046.0,Millions,USD,English,983.00
12,The Godfather Saga,Hollywood,1972,9.1,Paramount Pictures,7.20,291.0,Millions,USD,English,283.80
13,Shershaah Returns,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,450.00
14,Titanic Saga,Hollywood,1997,8.1,Paramount Pictures,200.00,2202.0,Millions,USD,English,2002.00
15,Captain America: The First Avenger Reborn,Hollywood,2011,6.8,Marvel Studios,216.70,370.6,Millions,USD,English,153.90
16,Pather Panchali Saga,Bollywood,1955,8.1,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,30000.00
17,Race 3,Bollywood,2018,1.7,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,1.30
18,The Shawshank Redemption,Hollywood,1994,9.2,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,48.30
19,Avatar,Hollywood,2009,7.7,20th Century Fox,237.00,2847.0,Millions,USD,English,2610.00
20,Doctor Strange in the Multiverse of Madness Redux,Hollywood,2022,7.1,Marvel Studios,200.00,954.8,Millions,USD,English,754.80
21,PK Redux,Bollywood,2014,8.2,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,7690.00
22,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.1,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,1600.00
23,Thor: The Dark World Reborn,Hollywood,2013,6.9,Marvel Studios,165.00,644.8,Millions,USD,English,479.80
24,Baahubali: The Beginning,Bollywood,2015,7.9,Arka Media Works,1.80,6.5,Billions,INR,Telugu,4.70
25,Pushpa: The Rise - Part 1 Legacy,Bollywood,2021,7.5,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,1.60
26,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,674.00
27,K.G.F: Chapter 2,Bollywood,2022,8.3,Hombale Films,1.00,12.5,Billions,INR,Kannada,11.50
28,Kabhi Khushi Kabhie Gham Saga,Bollywood,2001,7.3,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,970.00
29,Bajrangi Bhaijaan,Bollywood,2015,8.0,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,10790.00
30,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12
31,3 Idiots,Bollywood,2009,8.6,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,3450.00
32,Avengers: Infinity War Redux,Hollywood,2018,8.3,Marvel Studios,400.00,2048.0,Millions,USD,English,1648.00
33,Captain America: The Winter Soldier,Hollywood,2014,7.9,Marvel Studios,177.00,714.4,Millions,USD,English,537.40
34,The Pursuit of Happyness Saga,Hollywood,2006,8.1,Columbia Pictures,55.00,307.1,Millions,USD,English,252.10
35,Schindler's List,Hollywood,1993,8.8,Universal Pictures,22.00,322.2,Millions,USD,English,300.20
36,Sanju Reborn,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,4.90

In [84]:
Highest_Profitable_Movie=df[df.currency=="USD"]
Highest_Profitable_Movie[Highest_Profitable_Movie.Profit==Highest_Profitable_Movie.Profit.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit
19,Avatar,Hollywood,2009,7.7,20th Century Fox,237.0,2847.0,Millions,USD,English,2610.0

In [85]:
Lowest_Profitable_Movie=df[df.currency=="INR"]
Lowest_Profitable_Movie[Lowest_Profitable_Movie.Profit==Lowest_Profitable_Movie.Profit.min()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit
17,Race 3,Bollywood,2018,1.7,Salman Khan Films,1.8,3.1,Billions,INR,Hindi,1.3

In [86]:
df["Profit_Percentage"]=df.apply(lambda x:(x["revenue"]-x["budget"])/x["budget"]*100,axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage
0,Avengers: Endgame,Hollywood,2019,8.2,Marvel Studios,400.00,2798.0,Millions,USD,English,2398.00,599.500000
1,The Dark Knight Returns,Hollywood,2008,9.1,Syncopy,185.00,1006.0,Millions,USD,English,821.00,443.783784
2,Thor: Love and Thunder,Hollywood,2022,6.9,Marvel Studios,250.00,670.0,Millions,USD,English,420.00,168.000000
3,The Kashmir Files Legacy,Bollywood,2022,8.1,Zee Studios,250.00,3409.0,Millions,INR,Hindi,3159.00,1263.600000
4,RRR,Bollywood,2022,7.9,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,6.50,118.181818
5,Taare Zameen Par Redux,Bollywood,2007,8.2,NaN,120.00,1350.0,Millions,INR,Hindi,1230.00,1025.000000
6,Interstellar Legacy,Hollywood,2014,8.7,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,536.80,325.333333
7,Munna Bhai M.B.B.S. Returns,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,310.00,310.000000
8,Bajirao Mastani Saga,Bollywood,2015,7.3,NaN,1.40,3.5,Billions,INR,Hindi,2.10,150.000000
9,Parasite Redux,Hollywood,2019,8.7,NaN,15.50,263.1,Millions,USD,English,247.60,1597.419355
10,Gladiator Redux,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,357.50,347.087379
11,Jurassic Park Saga,Hollywood,1993,8.1,Universal Pictures,63.00,1046.0,Millions,USD,English,983.00,1560.317460
12,The Godfather Saga,Hollywood,1972,9.1,Paramount Pictures,7.20,291.0,Millions,USD,English,283.80,3941.666667
13,Shershaah Returns,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,450.00,90.000000
14,Titanic Saga,Hollywood,1997,8.1,Paramount Pictures,200.00,2202.0,Millions,USD,English,2002.00,1001.000000
15,Captain America: The First Avenger Reborn,Hollywood,2011,6.8,Marvel Studios,216.70,370.6,Millions,USD,English,153.90,71.019843
16,Pather Panchali Saga,Bollywood,1955,8.1,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,30000.00,42.857143
17,Race 3,Bollywood,2018,1.7,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,1.30,72.222222
18,The Shawshank Redemption,Hollywood,1994,9.2,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,48.30,193.200000
19,Avatar,Hollywood,2009,7.7,20th Century Fox,237.00,2847.0,Millions,USD,English,2610.00,1101.265823
20,Doctor Strange in the Multiverse of Madness Redux,Hollywood,2022,7.1,Marvel Studios,200.00,954.8,Millions,USD,English,754.80,377.400000
21,PK Redux,Bollywood,2014,8.2,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,7690.00,904.705882
22,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.1,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,1600.00,400.000000
23,Thor: The Dark World Reborn,Hollywood,2013,6.9,Marvel Studios,165.00,644.8,Millions,USD,English,479.80,290.787879
24,Baahubali: The Beginning,Bollywood,2015,7.9,Arka Media Works,1.80,6.5,Billions,INR,Telugu,4.70,261.111111
25,Pushpa: The Rise - Part 1 Legacy,Bollywood,2021,7.5,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,1.60,80.000000
26,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,674.00,374.444444
27,K.G.F: Chapter 2,Bollywood,2022,8.3,Hombale Films,1.00,12.5,Billions,INR,Kannada,11.50,1150.000000
28,Kabhi Khushi Kabhie Gham Saga,Bollywood,2001,7.3,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,970.00,248.717949
29,Bajrangi Bhaijaan,Bollywood,2015,8.0,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,10790.00,1198.888889
30,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12,3.773585
31,3 Idiots,Bollywood,2009,8.6,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,3450.00,627.272727
32,Avengers: Infinity War Redux,Hollywood,2018,8.3,Marvel Studios,400.00,2048.0,Millions,USD,English,1648.00,412.000000
33,Captain America: The Winter Soldier,Hollywood,2014,7.9,Marvel Studios,177.00,714.4,Millions,USD,English,537.40,303.615819
34,The Pursuit of Happyness Saga,Hollywood,2006,8.1,Columbia Pictures,55.00,307.1,Millions,USD,English,252.10,458.363636
35,Schindler's List,Hollywood,1993,8.8,Universal Pictures,22.00,322.2,Millions,USD,English,300.20,1364.545455
36,Sanju Reborn,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,4.90,490.000000

In [87]:
Most_Profit_Percentage=df[df.Profit_Percentage==df.Profit_Percentage.max()]
Most_Profit_Percentage

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage
12,The Godfather Saga,Hollywood,1972,9.1,Paramount Pictures,7.2,291.0,Millions,USD,English,283.8,3941.666667

In [88]:
Least_Profit_Percentage=df[df.Profit_Percentage==df.Profit_Percentage.min()]
Least_Profit_Percentage

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage
30,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12,3.773585

In [89]:
idx=df[df.studio=="Marvel Studios"].imdb_rating.idxmax()
df.loc[idx]

title                Avengers: Infinity War Redux
industry                                Hollywood
release_year                                 2018
imdb_rating                                   8.3
studio                             Marvel Studios
budget                                      400.0
revenue                                    2048.0
unit                                     Millions
currency                                      USD
language                                  English
Profit                                     1648.0
Profit_Percentage                           412.0
Name: 32, dtype: object

In [90]:
avg_HollyWood_IMDB=df[df.industry=="Hollywood"].imdb_rating.mean()
print("Average Hollywood Rating:",avg_HollyWood_IMDB)

Average Hollywood Rating: 8.135000000000002

In [91]:
avg_BollyWood_IMDB=df[df.industry=="Bollywood"].imdb_rating.mean()
print("Average BollyWood Rating:",avg_BollyWood_IMDB)

Average BollyWood Rating: 7.60625

In [92]:
avg_HollyWood_Revenue=df[df.industry=="Hollywood"].revenue.mean()
print("Average Hollywood revenue:",avg_HollyWood_Revenue)

Average Hollywood revenue: 928.8950000000001

In [93]:
avg_BollyWood_Revenue=df[df.industry=="Bollywood"].revenue.mean()
print("Average Bollywood revenue:",avg_BollyWood_Revenue)

Average Bollywood revenue: 7868.005882352942

In [94]:
df["age"]=df.apply(lambda x:2026-x["release_year"],axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage,age
0,Avengers: Endgame,Hollywood,2019,8.2,Marvel Studios,400.00,2798.0,Millions,USD,English,2398.00,599.500000,7
1,The Dark Knight Returns,Hollywood,2008,9.1,Syncopy,185.00,1006.0,Millions,USD,English,821.00,443.783784,18
2,Thor: Love and Thunder,Hollywood,2022,6.9,Marvel Studios,250.00,670.0,Millions,USD,English,420.00,168.000000,4
3,The Kashmir Files Legacy,Bollywood,2022,8.1,Zee Studios,250.00,3409.0,Millions,INR,Hindi,3159.00,1263.600000,4
4,RRR,Bollywood,2022,7.9,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,6.50,118.181818,4
5,Taare Zameen Par Redux,Bollywood,2007,8.2,NaN,120.00,1350.0,Millions,INR,Hindi,1230.00,1025.000000,19
6,Interstellar Legacy,Hollywood,2014,8.7,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,536.80,325.333333,12
7,Munna Bhai M.B.B.S. Returns,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,310.00,310.000000,23
8,Bajirao Mastani Saga,Bollywood,2015,7.3,NaN,1.40,3.5,Billions,INR,Hindi,2.10,150.000000,11
9,Parasite Redux,Hollywood,2019,8.7,NaN,15.50,263.1,Millions,USD,English,247.60,1597.419355,7
10,Gladiator Redux,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,357.50,347.087379,26
11,Jurassic Park Saga,Hollywood,1993,8.1,Universal Pictures,63.00,1046.0,Millions,USD,English,983.00,1560.317460,33
12,The Godfather Saga,Hollywood,1972,9.1,Paramount Pictures,7.20,291.0,Millions,USD,English,283.80,3941.666667,54
13,Shershaah Returns,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,450.00,90.000000,5
14,Titanic Saga,Hollywood,1997,8.1,Paramount Pictures,200.00,2202.0,Millions,USD,English,2002.00,1001.000000,29
15,Captain America: The First Avenger Reborn,Hollywood,2011,6.8,Marvel Studios,216.70,370.6,Millions,USD,English,153.90,71.019843,15
16,Pather Panchali Saga,Bollywood,1955,8.1,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,30000.00,42.857143,71
17,Race 3,Bollywood,2018,1.7,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,1.30,72.222222,8
18,The Shawshank Redemption,Hollywood,1994,9.2,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,48.30,193.200000,32
19,Avatar,Hollywood,2009,7.7,20th Century Fox,237.00,2847.0,Millions,USD,English,2610.00,1101.265823,17
20,Doctor Strange in the Multiverse of Madness Redux,Hollywood,2022,7.1,Marvel Studios,200.00,954.8,Millions,USD,English,754.80,377.400000,4
21,PK Redux,Bollywood,2014,8.2,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,7690.00,904.705882,12
22,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.1,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,1600.00,400.000000,31
23,Thor: The Dark World Reborn,Hollywood,2013,6.9,Marvel Studios,165.00,644.8,Millions,USD,English,479.80,290.787879,13
24,Baahubali: The Beginning,Bollywood,2015,7.9,Arka Media Works,1.80,6.5,Billions,INR,Telugu,4.70,261.111111,11
25,Pushpa: The Rise - Part 1 Legacy,Bollywood,2021,7.5,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,1.60,80.000000,5
26,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,674.00,374.444444,9
27,K.G.F: Chapter 2,Bollywood,2022,8.3,Hombale Films,1.00,12.5,Billions,INR,Kannada,11.50,1150.000000,4
28,Kabhi Khushi Kabhie Gham Saga,Bollywood,2001,7.3,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,970.00,248.717949,25
29,Bajrangi Bhaijaan,Bollywood,2015,8.0,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,10790.00,1198.888889,11
30,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12,3.773585,80
31,3 Idiots,Bollywood,2009,8.6,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,3450.00,627.272727,17
32,Avengers: Infinity War Redux,Hollywood,2018,8.3,Marvel Studios,400.00,2048.0,Millions,USD,English,1648.00,412.000000,8
33,Captain America: The Winter Soldier,Hollywood,2014,7.9,Marvel Studios,177.00,714.4,Millions,USD,English,537.40,303.615819,12
34,The Pursuit of Happyness Saga,Hollywood,2006,8.1,Columbia Pictures,55.00,307.1,Millions,USD,English,252.10,458.363636,20
35,Schindler's List,Hollywood,1993,8.8,Universal Pictures,22.00,322.2,Millions,USD,English,300.20,1364.545455,33
36,Sanju Reborn,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,4.90,490.000000,8

In [95]:
age_idx=df.age.idxmax()
df.iloc[age_idx]

title                It's a Wonderful Life
industry                         Hollywood
release_year                          1946
imdb_rating                            8.6
studio                       Liberty Films
budget                                3.18
revenue                                3.3
unit                              Millions
currency                               USD
language                           English
Profit                                0.12
Profit_Percentage                 3.773585
age                                     80
Name: 30, dtype: object

In [96]:
age_new_idx=df.age.min()
df.iloc[age_new_idx]

title                              RRR
industry                     Bollywood
release_year                      2022
imdb_rating                        7.9
studio               DVV Entertainment
budget                             5.5
revenue                           12.0
unit                          Billions
currency                           INR
language                        Telugu
Profit                             6.5
Profit_Percentage           118.181818
age                                  4
Name: 4, dtype: object