In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("movies.csv")

In [3]:
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu

In [6]:
Total_Number_Of_Movies=df.title.size
print("Total Number Of Movies In The List:",Total_Number_Of_Movies)

Total Number Of Movies In The List: 37

In [11]:
Total_Number_Of_Studios=df.studio.unique().size
print("Total Number Of Studio:",Total_Number_Of_Studios)

Total Number Of Studio: 22

In [13]:
Total_Number_Of_Languages=df.language.unique().size
print("Total Number Of Languages:",Total_Number_Of_Languages)

Total Number Of Languages: 5

In [24]:
Highest_IMDB_Rating=df[df.imdb_rating==df.imdb_rating.max()]
Highest_IMDB_Rating

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [25]:
Lowest_IMDB_Rating=df[df.imdb_rating==df.imdb_rating.min()]
Lowest_IMDB_Rating

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [34]:
Highest_Revenue_USD=df[df.currency=="USD"]
Highest_Revenue_USD[Highest_Revenue_USD.revenue==Highest_Revenue_USD.revenue.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English

In [37]:
Lowest_Revenue_Movie=df[df.unit=="Thousands"]
Lowest_Revenue_Movie[Lowest_Revenue_Movie.revenue==Lowest_Revenue_Movie.revenue.min()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali

In [39]:
Highest_Budget_Movie=df[df.currency=="USD"]
Highest_Budget_Movie[Highest_Budget_Movie.budget==Highest_Budget_Movie.budget.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English

In [35]:
Lowest_Budget_INR=df[df.currency=="INR"]
Lowest_Budget_INR[Lowest_Budget_INR.budget==Lowest_Budget_INR.budget.min()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada

In [41]:
df["Profit"]=df.apply(lambda x:x["revenue"]-x["budget"],axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,30000.00
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,754.80
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,479.80
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,674.00
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,420.00
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,48.30
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,536.80
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,252.10
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,357.50
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,2002.00
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,2610.00
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,283.80
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,821.00
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,300.20
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,983.00
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,247.60
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,2398.00
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,1648.00
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,153.90
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,537.40
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,1600.00
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,3450.00
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,970.00
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,2.10
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,1230.00
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,310.00
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,7690.00
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,4.90
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,3159.00
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,10790.00
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,1.30
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,450.00
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,11.50
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,1.60
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,6.50
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,4.70

In [43]:
Highest_Profitable_Movie=df[df.currency=="USD"]
Highest_Profitable_Movie[Highest_Profitable_Movie.Profit==Highest_Profitable_Movie.Profit.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English,2610.0

In [44]:
Lowest_Profitable_Movie=df[df.currency=="INR"]
Lowest_Profitable_Movie[Lowest_Profitable_Movie.Profit==Lowest_Profitable_Movie.Profit.min()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi,1.3

In [47]:
df["Profit_Percentage"]=df.apply(lambda x:(x["revenue"]-x["budget"])/x["budget"]*100,axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,30000.00,42.857143
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,754.80,377.400000
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,479.80,290.787879
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,674.00,374.444444
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,420.00,168.000000
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,48.30,193.200000
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,536.80,325.333333
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,252.10,458.363636
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,357.50,347.087379
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,2002.00,1001.000000
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12,3.773585
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,2610.00,1101.265823
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,283.80,3941.666667
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,821.00,443.783784
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,300.20,1364.545455
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,983.00,1560.317460
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,247.60,1597.419355
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,2398.00,599.500000
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,1648.00,412.000000
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,153.90,71.019843
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,537.40,303.615819
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,1600.00,400.000000
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,3450.00,627.272727
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,970.00,248.717949
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,2.10,150.000000
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,1230.00,1025.000000
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,310.00,310.000000
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,7690.00,904.705882
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,4.90,490.000000
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,3159.00,1263.600000
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,10790.00,1198.888889
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,1.30,72.222222
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,450.00,90.000000
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,11.50,1150.000000
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,1.60,80.000000
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,6.50,118.181818
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,4.70,261.111111

In [48]:
Most_Profit_Percentage=df[df.Profit_Percentage==df.Profit_Percentage.max()]
Most_Profit_Percentage

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.2,291.0,Millions,USD,English,283.8,3941.666667

In [49]:
Least_Profit_Percentage=df[df.Profit_Percentage==df.Profit_Percentage.min()]
Least_Profit_Percentage

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12,3.773585

In [54]:
idx=df[df.studio=="Marvel Studios"].imdb_rating.idxmax()
df.loc[idx]

title                Avengers: Endgame
industry                     Hollywood
release_year                      2019
imdb_rating                        8.4
studio                  Marvel Studios
budget                           400.0
revenue                         2798.0
unit                          Millions
currency                           USD
language                       English
Profit                          2398.0
Profit_Percentage                599.5
Name: 17, dtype: object

In [57]:
avg_HollyWood_IMDB=df[df.industry=="Hollywood"].imdb_rating.mean()
print("Average Hollywood Rating:",avg_HollyWood_IMDB)

Average Hollywood Rating: 8.130000000000003

In [58]:
avg_BollyWood_IMDB=df[df.industry=="Bollywood"].imdb_rating.mean()
print("Average BollyWood Rating:",avg_BollyWood_IMDB)

Average BollyWood Rating: 7.656250000000001

In [61]:
avg_HollyWood_Revenue=df[df.industry=="Hollywood"].revenue.mean()
print("Average Hollywood revenue:",avg_HollyWood_Revenue)

Average Hollywood revenue: 928.8950000000001

In [62]:
avg_BollyWood_Revenue=df[df.industry=="Bollywood"].revenue.mean()
print("Average Bollywood revenue:",avg_BollyWood_Revenue)

Average Bollywood revenue: 7868.005882352942

In [63]:
df["age"]=df.apply(lambda x:2026-x["release_year"],axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,Profit,Profit_Percentage,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,30000.00,42.857143,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,754.80,377.400000,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,479.80,290.787879,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,674.00,374.444444,9
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,420.00,168.000000,4
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,48.30,193.200000,32
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,536.80,325.333333,12
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,252.10,458.363636,20
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,357.50,347.087379,26
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,2002.00,1001.000000,29
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,0.12,3.773585,80
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,2610.00,1101.265823,17
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,283.80,3941.666667,54
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,821.00,443.783784,18
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,300.20,1364.545455,33
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,983.00,1560.317460,33
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,247.60,1597.419355,7
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,2398.00,599.500000,7
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,1648.00,412.000000,8
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,153.90,71.019843,15
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,537.40,303.615819,12
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,1600.00,400.000000,31
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,3450.00,627.272727,17
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,970.00,248.717949,25
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,2.10,150.000000,11
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,1230.00,1025.000000,19
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,310.00,310.000000,23
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,7690.00,904.705882,12
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,4.90,490.000000,8
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,3159.00,1263.600000,4
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,10790.00,1198.888889,11
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,1.30,72.222222,8
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,450.00,90.000000,5
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,11.50,1150.000000,4
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,1.60,80.000000,5
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,6.50,118.181818,4
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,4.70,261.111111,11

In [69]:
age_idx=df.age.idxmax()
df.iloc[age_idx]

title                It's a Wonderful Life
industry                         Hollywood
release_year                          1946
imdb_rating                            8.6
studio                       Liberty Films
budget                                3.18
revenue                                3.3
unit                              Millions
currency                               USD
language                           English
Profit                                0.12
Profit_Percentage                 3.773585
age                                     80
Name: 10, dtype: object

In [70]:
age_new_idx=df.age.min()
df.iloc[age_new_idx]

title                Thor: Love and Thunder
industry                           Hollywood
release_year                            2022
imdb_rating                              6.8
studio                        Marvel Studios
budget                                 250.0
revenue                                670.0
unit                                Millions
currency                                 USD
language                             English
Profit                                 420.0
Profit_Percentage                      168.0
age                                        4
Name: 4, dtype: object