In [1]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file with name "students_data.csv"
- Show the Top 5 rows

**Story:** ABC is maintaining the student records of a training institute. Read the student dataset and inspect the first five records.

In [2]:
#read the csv file into the variable "df"
df=pd.read_csv("students_data.csv")

#show the top 5 rows
df.head(5)

   student_id   name  course  join_year  score
0         101    ABC  Python       2021     88
1         102  Rahul    Java       2023     76
2         103  Sneha  Python       2020     91
3         104  Arjun     C++       2022     69
4         105  Priya  Python       2024     95

### <font color="purple">**Question2**</font>
- Add a new column **performance**.
- If **score** is greater than or equal to 80, return **'Excellent'**, otherwise return **'Needs Improvement'**.

In [3]:
#add the column "performance"
def performance(row):
    if row['score']>=80:
        return "Excellent"
    else:
        return "Needs Improvement"

df["performance"]=df.apply(performance,axis=1)

#show the df
df

   student_id    name  course  join_year  score        performance
0         101     ABC  Python       2021     88          Excellent
1         102   Rahul    Java       2023     76  Needs Improvement
2         103   Sneha  Python       2020     91          Excellent
3         104   Arjun     C++       2022     69  Needs Improvement
4         105   Priya  Python       2024     95          Excellent
5         106   Kiran    Java       2019     82          Excellent
6         107   Meera     C++       2021     74  Needs Improvement
7         108  Vikram  Python       2025     89          Excellent

### <font color="purple">**Question3**</font>

- Save the dataframe with the name **final_student_data.csv** and include only columns **student_id, name, course, score, performance**. Also set **index=False**.

In [4]:
#save the dataframe
df.to_csv("final_student_data.csv",
          columns=["student_id","name","course","score","performance"],
          index=False)